- name: install ubuntu dependencies
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-ldap
    - python-software-properties
    - python-httplib2
    - libfuse2
    - tmux
    - screen
    - autoconf
    - gcc
    - make
    - patch
    - tcsh
    - zsh
    - mosh

- name: install ubuntu dependencies
  apt: name={{ item }} state=present
  with_items:
    - fuse-utils
  when: ansible_distribution_major_version < '14'

- name: install ubuntu dependencies
  apt: name={{ item }} state=present
  with_items:
    - fuse
  when: ansible_distribution_major_version < '14'  

- name: Set timezone variables
  copy: content={{my_timezone}} dest=/etc/timezone owner=root group=root mode=0644 backup=yes 

- name: Remove old timezone link
  file: dest=/etc/localtime state=absent

- name: Update timezone
  file: src=/usr/share/zoneinfo/US/Arizona dest=/etc/localtime owner=root group=root state=link

 
- name: add necessary lines to rc.local
  lineinfile: dest=/etc/rc.local line="\n# this is for atmosphere\nif [ -x /etc/rc.local.atmo ]; then\n\t/etc/rc.local.atmo\nfi"

- name: create rc.local.atmo
  lineinfile: dest=/etc/rc.local.atmo create=yes state=present line='#!/bin/sh -e\ndepmod -a\nmodprobe acpiphp\nhostname {{ ansible_hostname }}\n'
 
- name: install motd
  copy: src=motd dest=/etc/motd.tail

- name: remove motd help text file, if present
  file: path=/etc/update-motd.d/10-help-text state=absent

- name: check ubuntu legal notice
  stat: path=/etc/legal
  register: atmo_common_ubuntu_legal

- name: move ubuntu legal file if it exists
  command: mv /etc/legal /etc/legal.disabled
  when: atmo_common_ubuntu_legal.stat.exists == True

